name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --filter="vitest-vscode-*" --frozen-lockfile
      - run: pnpm build
      - run: pnpm typecheck
      - run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: test
        run: pnpm test

      - name: test-e2e
        run: pnpm test-e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-results-${{ matrix.os }}'
          path: 'test-results/${{ matrix.os }}'

  test-legacy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: vitest 3.2
        run: node ./scripts/lower-vitest-version.js

      - run: pnpm install --prefer-offline
      - run: pnpm build

      - name: test
        run: pnpm test

      - name: test-e2e
        run: pnpm test-e2e:legacy

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-results-legacy-${{ matrix.os }}'
          path: 'test-results-legacy/${{ matrix.os }}'
